version: "3"
services:
  zookeeper1:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181'
      - '2888'
      - '3888'
    environment:
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=0.0.0.0:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
      - ALLOW_ANONYMOUS_LOGIN=yes

  zookeeper2:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181'
      - '2888'
      - '3888'
    environment:
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=zookeeper1:2888:3888,0.0.0.0:2888:3888,zookeeper3:2888:3888
      - ALLOW_ANONYMOUS_LOGIN=yes

  zookeeper3:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181'
      - '2888'
      - '3888'
    environment:
      - ZOO_SERVER_ID=3
      - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,0.0.0.0:2888:3888
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka1:
    image: bitnami/kafka:latest
    ports:
      - '9092'
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=3
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3

  kafka2:
    image: bitnami/kafka:latest
    ports:
      - '9092'
    environment:
      - KAFKA_CFG_BROKER_ID=2
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=3
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      
  kafka3:
    image: bitnami/kafka:latest
    ports:
      - '9092'
    environment:
      - KAFKA_CFG_BROKER_ID=3
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=3
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    
  mysql: 
    image: 
      mysql:latest
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    environment: 
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw 
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  sink-mysql: 
    image: 
      mysql:latest
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    environment: 
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw 
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  connector1: 
    build: 
      context: ./connector
    # image: debezium/connect:latest
    # volumes:
    #   - ./connector/confluentinc-kafka-connect-jdbc-10.7.0:/kafka/connect/confluentinc-kafka-connect-jdbc-10.7.0
    #   - ./connector/mysql-connector-j-8.0.32/mysql-connector-j-8.0.32.jar:/kafka/libs/mysql-connector-j-8.0.32.jar
    ports:
        - 8083:8083 
    environment:
      - BOOTSTRAP_SERVERS=kafka1:9092,kafka2:9092,kafka3:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=connect_configs
      - OFFSET_STORAGE_TOPIC=connect_offsets
      - STATUS_STORAGE_TOPIC=connect_statuses
    depends_on:
      - mysql
      - sink-mysql
      - kafka1
      - kafka2
      - kafka3


  connector2: 
    build: 
      context: ./connector
    # image: debezium/connect:latest
    # volumes:
    #   - ./connector/confluentinc-kafka-connect-jdbc-10.7.0:/kafka/connect/confluentinc-kafka-connect-jdbc-10.7.0
    #   - ./connector/mysql-connector-j-8.0.32/mysql-connector-j-8.0.32.jar:/kafka/libs/mysql-connector-j-8.0.32.jar
    ports:
        - 8084:8083 
    environment:
      - BOOTSTRAP_SERVERS=kafka1:9092,kafka2:9092,kafka3:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=connect_configs
      - OFFSET_STORAGE_TOPIC=connect_offsets
      - STATUS_STORAGE_TOPIC=connect_statuses
    depends_on:
      - mysql
      - sink-mysql
      - kafka1
      - kafka2
      - kafka3
