version: "3"
services:
  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  
  mysql: 
    image: 
      mysql:latest
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    environment: 
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw 
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  sink-mysql: 
    image: 
      mysql:latest
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    environment: 
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw 
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  connector1: 
    build: 
      context: ./connector
    # image: debezium/connect:latest
    # volumes:
    #   - ./connector/confluentinc-kafka-connect-jdbc-10.7.1:/kafka/connect/confluentinc-kafka-connect-jdbc-10.7.1
    #   - ./connector/mysql-connector-j-8.0.33/mysql-connector-j-8.0.33.jar:/kafka/libs/mysql-connector-j-8.0.33.jar
    ports:
        - 8083:8083 
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=connect_configs
      - OFFSET_STORAGE_TOPIC=connect_offsets
      - STATUS_STORAGE_TOPIC=connect_statuses
    depends_on:
      - mysql
      - sink-mysql
      - kafka


  connector2: 
    build: 
      context: ./connector
    # image: debezium/connect:latest
    # volumes:
    #   - ./connector/confluentinc-kafka-connect-jdbc-10.7.1:/kafka/connect/confluentinc-kafka-connect-jdbc-10.7.1
    #   - ./connector/mysql-connector-j-8.0.33/mysql-connector-j-8.0.33.jar:/kafka/libs/mysql-connector-j-8.0.33.jar
    ports:
        - 8084:8083 
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=connect_configs
      - OFFSET_STORAGE_TOPIC=connect_offsets
      - STATUS_STORAGE_TOPIC=connect_statuses
    depends_on:
      - mysql
      - sink-mysql
      - kafka
